name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Lint
        run: deno lint
      - name: Check formatting
        run: deno fmt --check
      - name: Test
        run: deno test --coverage=cov_profile
      - name: Generate Coverage Report
        run: deno coverage cov_profile --lcov --output=cov_profile.lcov